# Generated by Django 4.2.6 on 2023-10-27 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='activate_code',
        ),
        migrations.AddField(
            model_name='doctor',
            name='activate_url',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='confirance_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 12, 25, 49, 450358)),
        ),
    ]
