# Generated by Django 4.2.6 on 2023-10-30 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="confirance_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 30, 18, 3, 40, 489716)
            ),
        ),
    ]
