# Generated by Django 4.2.6 on 2023-11-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0002_patient_confirance_stastus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='confirance_date',
            field=models.DateTimeField(default=None),
        ),
    ]
