# Generated by Django 4.2.6 on 2023-10-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0002_remove_user_id_alter_user_user_id_doctor_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Date',
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=255)),
                ('additional_information', models.TextField(null=True)),
                ('confirance_date', models.DateTimeField()),
                ('doctor', models.ManyToManyField(to='med_app.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_app.user')),
            ],
        ),
    ]
