# Generated by Django 4.2.6 on 2023-11-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med_app", "0002_alter_patient_confirance_date"),
        ("med_app", "0004_remove_patient_doctor_patient_doctor"),
    ]

    operations = []
