#!/bin/bash

DJANGODIR=/home/MedBotApp
DJANGO_SETTINGS_MODULE=core.settings

cd $DJANGODIR
source ./venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

daphne -b 0.0.0.0 -p 8000 core.asgi:application
